---
env: production
ubuntu_user: ubuntu
region: ap-northeast-1
instance_tags:
  Name: shadowsocks_cluster_1z1s
  env: production_1z1s
vpc_tags:
  Name: shadowsocks_vpc_1z1s
  env: production_1z1s
vpc_cidr_block: 10.3.0.0/16
public_subnet_cidr_1: 10.3.11.0/24
available_zone_1: b
available_zone_2: c
sg_groups:
  - shadowsocks_inbound
  - shadowsocks_outbound
key_name: shadowsocks
instance_type: m3.medium
device_size: 50
exact_count: 1
vpc_header: "10.3."
manager_1_ip: "10.3.11.100"
worker_1_ip: "10.3.11.101"