---
env: production
ubuntu_user: ubuntu
region: ap-northeast-1
instance_tags:
  Name: shadowsocks_cluster
  env: production
vpc_tags:
  Name: shadowsocks_vpc
  env: production
vpc_cidr_block: 10.0.0.0/16
public_subnet_cidr_1: 10.0.10.0/24
private_subnet_cidr_1: 10.0.11.0/24
public_subnet_cidr_2: 10.0.12.0/24
private_subnet_cidr_2: 10.0.13.0/24
available_zone_1: b
available_zone_2: c
sg_groups:
  - shadowsocks_inbound
  - shadowsocks_outbound
key_name: shadowsocks
instance_type: m3.medium
device_size: 50
exact_count: 1
vpc_header: "10.0."
nginx_1_ip: "10.0.10.100"
nginx_2_ip: "10.0.12.100"
manager_1_ip: "10.0.11.100"
worker_1_ip: "10.0.11.101"
worker_3_ip: "10.0.13.100"
worker_2_ip: "10.0.13.101"