---
- name: public ssh security group
  ec2_group:
    name: shadowsocks_inbound
    tags:
      Name: shadowsocks
    description: allow public access
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 50000
        to_port: 50100
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: all
        cidr_ip: "{{ vpc_cidr_block }}"

- name: outbound group
  ec2_group:
    name: shadowsocks_outbound
    tags:
      Name: shadowsocks
    description: allow outbound connections to the internet
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0